backend:
  name: git-gateway
  branch: main
  base_url: https://natation-en-forme.netlify.app
  auth_endpoint: /.netlify/identity

media_folder: "images/posts"
public_folder: "/images/posts"

locale: 'fr'

collections:
  - name: "actualites"
    label: "Actualités"
    folder: "post"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date de publication", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - {label: "Image principale", name: "image", widget: "image", required: false}
      - {label: "Résumé (court)", name: "excerpt", widget: "text", required: false}
      - {label: "Contenu", name: "body", widget: "markdown"}
      - {label: "Publié", name: "published", widget: "boolean", default: true}
